---
repository_root: "{default.repository.root}/openjdk/{platform}/{architecture}"
version: 1.7.0_+
memory_heuristics:
  heap: 65
  permgen: 20 
  stack: 5
  native: 10
memory_initials:
  heap: 100%
  permgen: 100%
